### PR TITLE
Adds Complex Dynamic checking and OEM Item/Link checking, reworks

### PR DESCRIPTION
**Pull request by tomasg2012**
Adds Complex Dynamic Checking necessary for OEM items, while previously only did Basic types.  (Has an issue with systems with incomplete $metadata, and message spam with MessageRegistries, but seemed to only happen in one given system.)

Don't skip over OEM items and allocate links properly while checking the items.  Add option to enable oemchecks as needed.  (This is done in Validator, but should be handled when constructing our Resource)

Additionally adds some generators for the internal objects

Sans OemCheck:
capture4

With OemCheck:
capture2

Before ComplexCheck:
image

After ComplexCheck:
capture3

### CODE REVIEW

**Comment by mraineri** [comment]
6/7: Don't need to have a new option; "OemCheck" should always be on. Also would like to see a failure case where an unknown property is added inside of the "Oem" object.

**Comment by tomasg2012** [comment]
image

```
*** /redfish/v1
         Type (ServiceRoot), GET SUCCESS (time: 0.012313)
Oem.Bonobo has Redfish.DynamicPropertyPatterns annotation, but Pattern or Type properties missing
Oem.Contoso.Sorvice not defined in schema Resource (check version, spelling and casing)
          FAIL...
```

This is some of the stuff tested last week but wasn't present, the top Oem item being an empty Complex (dict), which triggers a nonspecific ERROR.  The bottom one is a Property added to a legitimate dict with an @odata.type, but is only considered a WARN, due to what I believe is the AdditionalProperty claim currently in the program.

**Comment by mraineri** [comment]
6/7: We should make a change to essentially ignore "additional properties = true" in the Oem context.

**Comment by tomasg2012** [comment]
`ERROR - Oem.Bonobo: OemObjects are required to be typecast`  Is the corrected message.

**Comment by mraineri** [comment]
Approved 6/21

**Pull request merged**
