### PR TITLE
Added OData-Version header

### PR DESCRIPTION
**Pull request by jautor**
On all GET requests, added the OData-Version header.

### CODE REVIEW

**Comment by tomasg2012** [comment]
I'm not sure what that option does, does this append the header to all get requests or does it check for that?  Shouldn't the change for the validator be to warn the user?

**Comment by jautor** [comment]
This is an OData-specified header to tell the Service what format/version the response should follow.  It's highly recommended for all clients to supply on every request (GET/PATCH/etc.)

**Comment by jautor** [comment]
Fix #58

**Comment by tomasg2012** [comment]
Ohh, now I understand, the client (this program) is supposed to send the odata version with the get request.  Pardon me.

**Comment by tomasg2012** [comment]
This fix should be fine, requests are only done through that function so it should be sufficient coverage

**Comment by mraineri** [comment]
Will be using the other PR to fix this

**Pull request closed without merging**
