### PR TITLE
Fix to Action validation overriding variable name, added log entry

### LINKED ISSUE #513: Validator cannot check invalid contents under Actions
Validator cannot check invalid contents under Actions - an actions such as “#Manager.ResetToDefaults_Fred” should fail validation since it’s not in the Manager schema. 
image

Tool Version: 2.2.1

### PR DESCRIPTION
**Pull request by tomasg2012**
Prevents overriding the error entry in messages

Added log entry for actions with bad names.

Fixes #513

### CODE REVIEW

**Comment by mraineri** [comment]
Looking over the output log, I see "errorActionBadName" tallied at the top, and I also see "errorActionBadName" in the summary of the affected resource, but I don't see it called out in the more specific errors details.

So, for example, I took public-rackmount1, and changed `#ComputerSystem.Reset` to `#ComputerSystem.Fred` in the system mockup.

At the top of the report I see "errorActionBadName" in the first block, but nothing calling it out for a specific URI in the second block like other errors.

image

And then in the URI report, I see the error on the right, which is good:

image

But when expanding the URI report, there's no mention of the error:

image

**Comment by tomasg2012** [comment]
Couldn't seem to find the problem with the message not appearing in the Error Logging block, so I am unsure if there's more to it.  if the branch still doesn't work, please post any more info.

**Comment by mraineri** [comment]
Updates look good! Haven't found a regression yet

**Comment by mraineri** [comment]
Approved 3/17

**Pull request merged**
